#!/sbin/runscript
# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

PIDFILE=/var/run/${SVCNAME}.pid

depend() {
	need net
	use logger
}

start() {
	ebegin "Starting ${SVCNAME}"
		start-stop-daemon --start --quiet --background \
		--pidfile ${PIDFILE} \
		--exec /usr/bin/hg serve -- --daemon \
			--pid-file=${PIDFILE} \
			${HGSERVE_OPTS}
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
		start-stop-daemon --stop --quiet \
		--pidfile ${PIDFILE}
	eend $?
}
