#!/bin/bash

die() {
  echo "$*" >&2
  exit 1
}

[[ -z $1 ]] && die "Missing argument"

for l in $(scanelf -n "$@" | awk '/^ET/{gsub(/,/,"\n",$2);print $2}' | sort -u); do
  [[ $l = libgcc* || $l = libstdc* ]] && continue
  lib="$(find /lib /usr/lib -maxdepth 2 -name "$l")"
  [[ -z $lib ]] && echo "Could not find $l" >&2 && continue
  pkg=$(qfile -C -e -q "$lib")
  [[ -z $pkg ]] && echo "No package found containing $lib" >&2 && continue
  echo $pkg | eix '-|*' --format '<markedversions:NAMESLOT>'
done | sort -u 
